#ifndef GOFLY_CONFIG_BOARD_MAP_H
#define GOFLY_CONFIG_BOARD_MAP_H

#define GOFLY_BOARD_MAP_VERSION 1U
#define GOFLY_MCU_ID_EXPECTED "STM32F405RGT6"
#define GOFLY_MCU_PACKAGE_EXPECTED "LQFP64"

#define GOFLY_GPIO_PORT_A 0U
#define GOFLY_GPIO_PORT_B 1U
#define GOFLY_GPIO_PORT_C 2U
#define GOFLY_GPIO_PORT_D 3U
#define GOFLY_GPIO_PORT_E 4U
#define GOFLY_GPIO_PIN_ID(port, pin) (((port) * 16U) + (pin))

#define GOFLY_PORT_NAME_A "GPIOA"
#define GOFLY_PORT_NAME_B "GPIOB"
#define GOFLY_PORT_NAME_C "GPIOC"
#define GOFLY_PORT_NAME_D "GPIOD"
#define GOFLY_PORT_NAME_E "GPIOE"
#define GOFLY_GPIO_PORT_H 7U
#define GOFLY_HSE_IN_PORT GOFLY_GPIO_PORT_H
#define GOFLY_HSE_IN_PIN 0U
#define GOFLY_HSE_OUT_PORT GOFLY_GPIO_PORT_H
#define GOFLY_HSE_OUT_PIN 1U
#define GOFLY_HSE_FREQUENCY_HZ 8000000UL
#define GOFLY_SIGNAL_NAME_HSE_IN "RCC_OSC_IN"
#define GOFLY_SIGNAL_NAME_HSE_OUT "RCC_OSC_OUT"

#define GOFLY_IMU_SPI_INSTANCE 1U
#define GOFLY_IMU_SPI_NAME "SPI1"
#define GOFLY_IMU_SCK_PORT GOFLY_GPIO_PORT_A
#define GOFLY_IMU_SCK_PIN 5U
#define GOFLY_IMU_MISO_PORT GOFLY_GPIO_PORT_A
#define GOFLY_IMU_MISO_PIN 6U
#define GOFLY_IMU_MOSI_PORT GOFLY_GPIO_PORT_A
#define GOFLY_IMU_MOSI_PIN 7U
#define GOFLY_IMU_CS_PORT GOFLY_GPIO_PORT_B
#define GOFLY_IMU_CS_PIN 0U
#define GOFLY_IMU_INT1_PORT GOFLY_GPIO_PORT_C
#define GOFLY_IMU_INT1_PIN 4U
#define GOFLY_SIGNAL_NAME_IMU_SCK "IMU_SCK"
#define GOFLY_SIGNAL_NAME_IMU_MISO "IMU_MISO"
#define GOFLY_SIGNAL_NAME_IMU_MOSI "IMU_MOSI"
#define GOFLY_SIGNAL_NAME_IMU_CS "IMU_CS"
#define GOFLY_SIGNAL_NAME_IMU_INT1 "IMU_INT1"

#define GOFLY_FLASH_SPI_INSTANCE 3U
#define GOFLY_FLASH_SPI_NAME "SPI3"
#define GOFLY_FLASH_SCK_PORT GOFLY_GPIO_PORT_B
#define GOFLY_FLASH_SCK_PIN 3U
#define GOFLY_FLASH_MISO_PORT GOFLY_GPIO_PORT_B
#define GOFLY_FLASH_MISO_PIN 4U
#define GOFLY_FLASH_MOSI_PORT GOFLY_GPIO_PORT_B
#define GOFLY_FLASH_MOSI_PIN 5U
#define GOFLY_FLASH_CS_PORT GOFLY_GPIO_PORT_B
#define GOFLY_FLASH_CS_PIN 1U
#define GOFLY_SIGNAL_NAME_FLASH_SCK "FLASH_SCK"
#define GOFLY_SIGNAL_NAME_FLASH_MISO "FLASH_MISO"
#define GOFLY_SIGNAL_NAME_FLASH_MOSI "FLASH_MOSI"
#define GOFLY_SIGNAL_NAME_FLASH_CS "FLASH_CS"

#define GOFLY_OSD_SPI_INSTANCE 2U
#define GOFLY_OSD_SPI_NAME "SPI2"
#define GOFLY_OSD_SCK_PORT GOFLY_GPIO_PORT_B
#define GOFLY_OSD_SCK_PIN 13U
#define GOFLY_OSD_MISO_PORT GOFLY_GPIO_PORT_B
#define GOFLY_OSD_MISO_PIN 14U
#define GOFLY_OSD_MOSI_PORT GOFLY_GPIO_PORT_B
#define GOFLY_OSD_MOSI_PIN 15U
#define GOFLY_OSD_CS_PORT GOFLY_GPIO_PORT_B
#define GOFLY_OSD_CS_PIN 12U
#define GOFLY_OSD_RESET_PORT GOFLY_GPIO_PORT_A
#define GOFLY_OSD_RESET_PIN 1U
#define GOFLY_SIGNAL_NAME_OSD_SCK "OSD_SCK"
#define GOFLY_SIGNAL_NAME_OSD_MISO "OSD_MISO"
#define GOFLY_SIGNAL_NAME_OSD_MOSI "OSD_MOSI"
#define GOFLY_SIGNAL_NAME_OSD_CS "OSD_CS"
#define GOFLY_SIGNAL_NAME_OSD_RESET "OSD_RESET"

#define GOFLY_BARO_I2C_INSTANCE 1U
#define GOFLY_BARO_I2C_NAME "I2C1"
#define GOFLY_BARO_SCL_PORT GOFLY_GPIO_PORT_B
#define GOFLY_BARO_SCL_PIN 8U
#define GOFLY_BARO_SDA_PORT GOFLY_GPIO_PORT_B
#define GOFLY_BARO_SDA_PIN 9U
#define GOFLY_BMP280_I2C_ADDRESS 0x76U
#define GOFLY_SIGNAL_NAME_BARO_SCL "BARO_SCL"
#define GOFLY_SIGNAL_NAME_BARO_SDA "BARO_SDA"

#define GOFLY_CRSF_UART_INSTANCE 1U
#define GOFLY_CRSF_UART_NAME "USART1"
#define GOFLY_CRSF_TX_PORT GOFLY_GPIO_PORT_A
#define GOFLY_CRSF_TX_PIN 9U
#define GOFLY_CRSF_RX_PORT GOFLY_GPIO_PORT_A
#define GOFLY_CRSF_RX_PIN 10U
#define GOFLY_CRSF_UART_BAUD 420000UL
#define GOFLY_CRSF_HALF_DUPLEX 1U
#define GOFLY_SIGNAL_NAME_CRSF_TX "CRSF_TX"
#define GOFLY_SIGNAL_NAME_CRSF_RX "CRSF_RX"

#define GOFLY_GPS_UART_INSTANCE 3U
#define GOFLY_GPS_UART_NAME "USART3"
#define GOFLY_GPS_TX_PORT GOFLY_GPIO_PORT_B
#define GOFLY_GPS_TX_PIN 10U
#define GOFLY_GPS_RX_PORT GOFLY_GPIO_PORT_B
#define GOFLY_GPS_RX_PIN 11U
#define GOFLY_GPS_UART_BAUD 57600UL
#define GOFLY_SIGNAL_NAME_GPS_TX "GPS_TX"
#define GOFLY_SIGNAL_NAME_GPS_RX "GPS_RX"

#define GOFLY_VTX_UART_INSTANCE 4U
#define GOFLY_VTX_UART_NAME "UART4"
#define GOFLY_VTX_TX_PORT GOFLY_GPIO_PORT_C
#define GOFLY_VTX_TX_PIN 10U
#define GOFLY_VTX_RX_PORT GOFLY_GPIO_PORT_C
#define GOFLY_VTX_RX_PIN 11U
#define GOFLY_SIGNAL_NAME_VTX_TX "VTX_MSP_TX"
#define GOFLY_SIGNAL_NAME_VTX_RX "VTX_MSP_RX"

#define GOFLY_ESC_UART_INSTANCE 2U
#define GOFLY_ESC_UART_NAME "USART2"
#define GOFLY_ESC_TX_PORT GOFLY_GPIO_PORT_A
#define GOFLY_ESC_TX_PIN 2U
#define GOFLY_ESC_RX_PORT GOFLY_GPIO_PORT_A
#define GOFLY_ESC_RX_PIN 3U
#define GOFLY_SIGNAL_NAME_ESC_TX "ESC_TELEM_TX"
#define GOFLY_SIGNAL_NAME_ESC_RX "ESC_TELEM_RX"

#define GOFLY_MOTOR_TIMER_INSTANCE 3U
#define GOFLY_MOTOR_TIMER_NAME "TIM3"
#define GOFLY_MOTOR1_PORT GOFLY_GPIO_PORT_C
#define GOFLY_MOTOR1_PIN 6U
#define GOFLY_MOTOR1_CHANNEL 1U
#define GOFLY_MOTOR2_PORT GOFLY_GPIO_PORT_C
#define GOFLY_MOTOR2_PIN 7U
#define GOFLY_MOTOR2_CHANNEL 2U
#define GOFLY_MOTOR3_PORT GOFLY_GPIO_PORT_C
#define GOFLY_MOTOR3_PIN 8U
#define GOFLY_MOTOR3_CHANNEL 3U
#define GOFLY_MOTOR4_PORT GOFLY_GPIO_PORT_C
#define GOFLY_MOTOR4_PIN 9U
#define GOFLY_MOTOR4_CHANNEL 4U
#define GOFLY_MOTOR_TIMER_PRESCALER 0U
#define GOFLY_MOTOR_TIMER_PERIOD_TICKS 279U
#define GOFLY_SIGNAL_NAME_MOTOR1 "MOTOR1_DSHOT"
#define GOFLY_SIGNAL_NAME_MOTOR2 "MOTOR2_DSHOT"
#define GOFLY_SIGNAL_NAME_MOTOR3 "MOTOR3_DSHOT"
#define GOFLY_SIGNAL_NAME_MOTOR4 "MOTOR4_DSHOT"

#define GOFLY_ADC_INSTANCE 1U
#define GOFLY_ADC_NAME "ADC1"
#define GOFLY_BATTERY_ADC_PORT GOFLY_GPIO_PORT_C
#define GOFLY_BATTERY_ADC_PIN 0U
#define GOFLY_CURRENT_ADC_PORT GOFLY_GPIO_PORT_C
#define GOFLY_CURRENT_ADC_PIN 1U
#define GOFLY_SIGNAL_NAME_BATTERY_ADC "VBAT_SENSE"
#define GOFLY_SIGNAL_NAME_CURRENT_ADC "CURRENT_SENSE"

#define GOFLY_USB_INSTANCE "USB_OTG_FS"
#define GOFLY_USB_DM_PORT GOFLY_GPIO_PORT_A
#define GOFLY_USB_DM_PIN 11U
#define GOFLY_USB_DP_PORT GOFLY_GPIO_PORT_A
#define GOFLY_USB_DP_PIN 12U
#define GOFLY_USB_VBUS_PORT GOFLY_GPIO_PORT_A
#define GOFLY_USB_VBUS_PIN 8U
#define GOFLY_SIGNAL_NAME_USB_DM "USB_DM"
#define GOFLY_SIGNAL_NAME_USB_DP "USB_DP"
#define GOFLY_SIGNAL_NAME_USB_VBUS "USB_VBUS_SENSE"

#define GOFLY_SWDIO_PORT GOFLY_GPIO_PORT_A
#define GOFLY_SWDIO_PIN 13U
#define GOFLY_SWCLK_PORT GOFLY_GPIO_PORT_A
#define GOFLY_SWCLK_PIN 14U
#define GOFLY_NRST_SIGNAL_NAME "NRST"

#define GOFLY_LED_STRIP_PORT GOFLY_GPIO_PORT_A
#define GOFLY_LED_STRIP_PIN 0U
#define GOFLY_BUZZER_PORT GOFLY_GPIO_PORT_C
#define GOFLY_BUZZER_PIN 5U
#define GOFLY_STATUS_LED_PORT GOFLY_GPIO_PORT_C
#define GOFLY_STATUS_LED_PIN 13U
#define GOFLY_TIM6_INSTANCE 6U
#define GOFLY_TIM6_NAME "TIM6"
#define GOFLY_TIM6_TICK_RATE_HZ 1000U
#define GOFLY_SIGNAL_NAME_LED_STRIP "LED_STRIP"
#define GOFLY_SIGNAL_NAME_BUZZER "BUZZER"
#define GOFLY_SIGNAL_NAME_STATUS_LED "STATUS_LED"

#if (GOFLY_IMU_SCK_PORT == GOFLY_GPIO_PORT_E) || \
    (GOFLY_IMU_MISO_PORT == GOFLY_GPIO_PORT_E) || \
    (GOFLY_IMU_MOSI_PORT == GOFLY_GPIO_PORT_E) || \
    (GOFLY_IMU_CS_PORT == GOFLY_GPIO_PORT_E) || \
    (GOFLY_IMU_INT1_PORT == GOFLY_GPIO_PORT_E) || \
    (GOFLY_FLASH_SCK_PORT == GOFLY_GPIO_PORT_E) || \
    (GOFLY_FLASH_MISO_PORT == GOFLY_GPIO_PORT_E) || \
    (GOFLY_FLASH_MOSI_PORT == GOFLY_GPIO_PORT_E) || \
    (GOFLY_FLASH_CS_PORT == GOFLY_GPIO_PORT_E) || \
    (GOFLY_OSD_SCK_PORT == GOFLY_GPIO_PORT_E) || \
    (GOFLY_OSD_MISO_PORT == GOFLY_GPIO_PORT_E) || \
    (GOFLY_OSD_MOSI_PORT == GOFLY_GPIO_PORT_E) || \
    (GOFLY_OSD_CS_PORT == GOFLY_GPIO_PORT_E) || \
    (GOFLY_OSD_RESET_PORT == GOFLY_GPIO_PORT_E) || \
    (GOFLY_BARO_SCL_PORT == GOFLY_GPIO_PORT_E) || \
    (GOFLY_BARO_SDA_PORT == GOFLY_GPIO_PORT_E) || \
    (GOFLY_CRSF_TX_PORT == GOFLY_GPIO_PORT_E) || \
    (GOFLY_CRSF_RX_PORT == GOFLY_GPIO_PORT_E) || \
    (GOFLY_GPS_TX_PORT == GOFLY_GPIO_PORT_E) || \
    (GOFLY_GPS_RX_PORT == GOFLY_GPIO_PORT_E) || \
    (GOFLY_VTX_TX_PORT == GOFLY_GPIO_PORT_E) || \
    (GOFLY_VTX_RX_PORT == GOFLY_GPIO_PORT_E) || \
    (GOFLY_ESC_TX_PORT == GOFLY_GPIO_PORT_E) || \
    (GOFLY_ESC_RX_PORT == GOFLY_GPIO_PORT_E) || \
    (GOFLY_MOTOR1_PORT == GOFLY_GPIO_PORT_E) || \
    (GOFLY_MOTOR2_PORT == GOFLY_GPIO_PORT_E) || \
    (GOFLY_MOTOR3_PORT == GOFLY_GPIO_PORT_E) || \
    (GOFLY_MOTOR4_PORT == GOFLY_GPIO_PORT_E) || \
    (GOFLY_BATTERY_ADC_PORT == GOFLY_GPIO_PORT_E) || \
    (GOFLY_CURRENT_ADC_PORT == GOFLY_GPIO_PORT_E) || \
    (GOFLY_USB_DM_PORT == GOFLY_GPIO_PORT_E) || \
    (GOFLY_USB_DP_PORT == GOFLY_GPIO_PORT_E) || \
    (GOFLY_USB_VBUS_PORT == GOFLY_GPIO_PORT_E) || \
    (GOFLY_SWDIO_PORT == GOFLY_GPIO_PORT_E) || \
    (GOFLY_SWCLK_PORT == GOFLY_GPIO_PORT_E) || \
    (GOFLY_LED_STRIP_PORT == GOFLY_GPIO_PORT_E) || \
    (GOFLY_BUZZER_PORT == GOFLY_GPIO_PORT_E) || \
    (GOFLY_STATUS_LED_PORT == GOFLY_GPIO_PORT_E)
#error "GPIOE is not available on the STM32F405RGT6 board map"
#endif

#if GOFLY_GPIO_PIN_ID(GOFLY_MOTOR1_PORT, GOFLY_MOTOR1_PIN) == \
    GOFLY_GPIO_PIN_ID(GOFLY_MOTOR2_PORT, GOFLY_MOTOR2_PIN) || \
    GOFLY_GPIO_PIN_ID(GOFLY_MOTOR1_PORT, GOFLY_MOTOR1_PIN) == \
    GOFLY_GPIO_PIN_ID(GOFLY_MOTOR3_PORT, GOFLY_MOTOR3_PIN) || \
    GOFLY_GPIO_PIN_ID(GOFLY_MOTOR1_PORT, GOFLY_MOTOR1_PIN) == \
    GOFLY_GPIO_PIN_ID(GOFLY_MOTOR4_PORT, GOFLY_MOTOR4_PIN) || \
    GOFLY_GPIO_PIN_ID(GOFLY_MOTOR2_PORT, GOFLY_MOTOR2_PIN) == \
    GOFLY_GPIO_PIN_ID(GOFLY_MOTOR3_PORT, GOFLY_MOTOR3_PIN) || \
    GOFLY_GPIO_PIN_ID(GOFLY_MOTOR2_PORT, GOFLY_MOTOR2_PIN) == \
    GOFLY_GPIO_PIN_ID(GOFLY_MOTOR4_PORT, GOFLY_MOTOR4_PIN) || \
    GOFLY_GPIO_PIN_ID(GOFLY_MOTOR3_PORT, GOFLY_MOTOR3_PIN) == \
    GOFLY_GPIO_PIN_ID(GOFLY_MOTOR4_PORT, GOFLY_MOTOR4_PIN)
#error "Motor output pins must be unique"
#endif

#if GOFLY_USB_DM_PORT != GOFLY_GPIO_PORT_A || GOFLY_USB_DM_PIN != 11U || \
    GOFLY_USB_DP_PORT != GOFLY_GPIO_PORT_A || GOFLY_USB_DP_PIN != 12U
#error "USB FS must use PA11 USB_DM and PA12 USB_DP"
#endif

#if GOFLY_BATTERY_ADC_PORT != GOFLY_GPIO_PORT_C || \
    GOFLY_BATTERY_ADC_PIN != 0U || \
    GOFLY_CURRENT_ADC_PORT != GOFLY_GPIO_PORT_C || \
    GOFLY_CURRENT_ADC_PIN != 1U
#error "ADC inputs must use PC0 battery sense and PC1 current sense"
#endif

#endif
