#ifndef GOFLY_CONFIG_FLIGHT_CONFIG_H
#define GOFLY_CONFIG_FLIGHT_CONFIG_H

#define GOFLY_IMU_RATE_HZ 1000U
#define GOFLY_ATTITUDE_RATE_HZ 500U
#define GOFLY_DSHOT_RATE_HZ 1000U
#define GOFLY_GPS_BAUD 57600UL
#define GOFLY_CRSF_BAUD 420000UL
#define GOFLY_IMU_TIMEOUT_US 3000UL
#define GOFLY_ESC_TELEMETRY_TIMEOUT_MS 100UL

#define GOFLY_ATTITUDE_PERIOD_US (1000000UL / GOFLY_ATTITUDE_RATE_HZ)
#define GOFLY_DSHOT_PERIOD_US (1000000UL / GOFLY_DSHOT_RATE_HZ)

#if GOFLY_IMU_RATE_HZ == 0U || GOFLY_ATTITUDE_RATE_HZ == 0U || \
    GOFLY_DSHOT_RATE_HZ == 0U || GOFLY_IMU_TIMEOUT_US == 0UL || \
    GOFLY_ESC_TELEMETRY_TIMEOUT_MS == 0UL
#error "Flight timing constants must be nonzero"
#endif

#endif
