#ifndef GOFLY_CONFIG_SAFETY_CONFIG_H
#define GOFLY_CONFIG_SAFETY_CONFIG_H

#ifndef GOFLY_FLIGHT_ENABLE
#define GOFLY_FLIGHT_ENABLE 0
#endif

#ifndef GOFLY_REAL_OUTPUT
#define GOFLY_REAL_OUTPUT 0
#endif

#ifndef GOFLY_RTH_REAL_OUTPUT
#define GOFLY_RTH_REAL_OUTPUT 0
#endif

#ifndef GOFLY_DSHOT_HW_BACKEND
#define GOFLY_DSHOT_HW_BACKEND 0
#endif

#define GOFLY_BENCH_MODE_DEFAULT 1

#endif
